[build]
builder = "nixpacks"
buildCommand = "npm i -g pnpm && pnpm install && pnpm run build:all"

[deploy]
startCommand = "cd server && npx prisma db push --schema=./prisma/schema.prisma && node --import tsx src/index.ts"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
